# Generated by Django 4.2.20 on 2025-05-06 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
                ('imagen_categoria', models.ImageField(blank=True, null=True, upload_to='categoria/')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50)),
                ('descripcion_producto', models.TextField()),
                ('precio_producto', models.IntegerField()),
                ('cantidad_producto', models.IntegerField(default=0)),
                ('creacion_producto', models.DateTimeField(auto_now_add=True)),
                ('imagen_producto', models.ImageField(blank=True, null=True, upload_to='producto/')),
                ('id_categoria', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.categorias')),
            ],
        ),
    ]
