# Generated by Django 4.2.20 on 2025-05-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('correo_usuario', models.CharField(max_length=100)),
                ('contraseña_usuario', models.CharField(max_length=100)),
            ],
        ),
    ]
