# Generated by Django 4.2.21 on 2025-05-08 02:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_carrito_elementocarrito_carritoproducto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='creacion_producto',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
