# Generated by Django 4.2.21 on 2025-05-14 01:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_producto_creacion_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_envio', models.CharField(choices=[('domicilio', 'Envío a domicilio'), ('tienda', 'Retiro en tienda')], max_length=20)),
                ('costo', models.PositiveIntegerField(default=0)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('sede', models.CharField(blank=True, max_length=100, null=True)),
                ('carrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.carrito')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.carrito')),
            ],
        ),
    ]
