# Generated by Django 4.2.21 on 2025-05-21 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_metodoentrega_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_producto',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='creacion_producto',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
