# Generated by Django 4.2.20 on 2025-05-22 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_producto_codigo_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido_usuario',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('monto_pedido', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.usuario')),
            ],
        ),
    ]
