# Generated by Django 4.2.20 on 2025-06-30 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_ventas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_pedido',
            name='subtotal',
        ),
    ]
