# Generated by Django 4.2.20 on 2025-07-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo_usuario',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
