# Generated by Django 4.2.20 on 2025-07-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_usuario_correo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo_usuario',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
