# Generated by Django 4.2.20 on 2025-07-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_usuario_correo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='observaciones',
        ),
        migrations.AlterField(
            model_name='ventas',
            name='estado_pago',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('fallido', 'Fallido')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=50),
        ),
    ]
