# Generated by Django 4.2.20 on 2025-07-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_metodopago_pedido_metodo_envio_pedido_metodo_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='metodo_envio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='metodo_pago',
        ),
    ]
