# Generated by Django 4.2.20 on 2025-07-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_pedido_metodo_envio_remove_pedido_metodo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='metodo_pago',
        ),
    ]
